export const ApiErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  DUPLICATE_ACCOUNT: 'DUPLICATE_ACCOUNT',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ApiErrorCodeValue = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
